FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

COPY ./apps/answer-corrector ./apps/answer-corrector
COPY ./apps/lluis ./apps/lluis/
COPY ./apps/web ./apps/web/

RUN npm install

WORKDIR /app/apps/web
CMD [ "npm", "run", "dev", "--", "--host" ]
